### PR TITLE
Added storage path to fixes #14

### LINKED ISSUE #14: Storage path in options (job)
Hello,

In the option block, i don't see the "storage path" parameter as on the interface

image

Any idea when it will be available ?

Thanks

### PR DESCRIPTION
**Pull request by moosilauke18**

### CODE REVIEW

**Comment by bmx0r** [comment]
any ETA when this will be merged? :) Thanks for the job btw 👍 😄

**Comment by dusty73** [comment]
Is there any timeline to merge this feature? It would be very helpful

**Comment by bjtox** [comment]
this feature would solve a issue for us

**Comment by fdevans** [comment]
We will be putting some time into reviewing/testing these soon.  We need some validation tests added to confirm functionality for both `true` and `false` scenarios before we could merge this if someone can add those.

**Comment by bzuelke** [comment]
This is such a needed feature

**Comment by shatazone** [comment]
Would anyone please merge this feature? It's needed urgently

**Comment by fdevans** [comment]
Merged to a local branch to add tests and finish the requests made previously.  Please feel free to add to Pull Requests when we need fixes.

**Pull request merged**
