### PR TITLE
Add import job

### PR DESCRIPTION
**Pull request by moosilauke18**
Fixing `description` from `decription` caused the one ideompotency to fail. It's somewhere either on go-rundeck or rundeck itself.  I've changed it to cause it to pass.

### CODE REVIEW

**Comment by doriitamar** [comment]
Hi @moosilauke18! Is this something that is planned to be merged? It's a useful feature to have on this provider, is there anything I can do to help make that happen?

**Comment by doriitamar** [comment]
@ProTip

**Comment by fdevans** [comment]
Hi @moosilauke18 we can review this in an upcoming effort if you can resolve the conflict in `resource_job.go`

**Comment by fdevans** [comment]
If someone can provide some clearer acceptance tests I can perform I can get this merged.  I'm not exactly clear on the use case.

**Comment by andrea-berling** [comment]
> If someone can provide some clearer acceptance tests I can perform I can get this merged. I'm not exactly clear on the use case.

A use case for this would be transitioning from an existing manual Rundeck configuration into a Terraform-driven one using importing and automatic config generation (useful links: https://opentofu.org/docs/language/import/ and https://opentofu.org/docs/language/import/generating-configuration/)

**Comment by andrea-berling** [comment]
@fdevans Hey Forrest 👋 I revived this effort and opened up a new Pull Request: https://github.com/rundeck/terraform-provider-rundeck/pull/130. Could you please take a look when you get a chance and possibly merge and release this change? Any feedback on the code and progress of the merge is highly appreciated 🙂

**Comment by fdevans** [comment]
#130 was approved!

**Pull request closed without merging**
