### PR TITLE
Add orchestrator options, and maintenance

### PR DESCRIPTION
**Pull request by sorenmat**
This is work based upon #29 and addresses #31 

The code is split into two commits one with actual code and one with the vendoring

This allow us to configure the orchestrator options for Rundeck

Added automated Acceptance tests, and updated go modules

### CODE REVIEW

**Comment by sorenmat** [comment]
Adding @ProTip for a possible review?

**Comment by sorenmat** [comment]
Any change for a review, or suggestions?

**Comment by ProTip** [comment]
Hi @sorenmat ,

Thanks for this and sorry for the late response.. I'm planning on reviewing all PRs thoroughly early next week.

In the meantime:

* Is the Go upgrade necessary for the added functionality?
It may be better to upgrade in a separate PR

* Could you rebase on master?
A basic test harness has been setup to run acceptance tests on CircleCI. That should get it running.

Thanks!

**Comment by sorenmat** [comment]
@ProTip removed all the nice to have stuff, and left only the code functionality. Please review :)

**Comment by fardin01** [comment]
@qualman @fdevans @ltamaster Any chance one of you could review and merge this, please?

**Comment by Wicaeed** [comment]
Any chance this can be merged soon? It would be awesome to manage these settings in TF!

**Comment by fdevans** [comment]
This is missing the Highest/Lowest Orchestrator option.  Was that intentional?  If so, why?

Screen Shot 2022-02-02 at 2 33 52 PM
.

**Comment by fdevans** [comment]
OK.  If anyone wants to finish this out with the remaining options we will review and approve.

**Pull request merged**
