### PR TITLE
Import project

### PR DESCRIPTION
**Pull request by moosilauke18**

### CODE REVIEW

**Comment by fdevans** [comment]
@moosilauke18 Can you please provide relevant documentation updates and steps to validate that this works?

**Comment by ikorchynskyi** [comment]
Could someone check and merge this? PR seems to be working, and this one feature is really useful (tbh more like mandatory in case when you need to integrate already existing Rundeck projects

**Comment by fdevans** [comment]
@ikorchynskyi we asked previously for documentation and validation tests to be added.  Not sure if @moosilauke18 wants to do that, but if you want to contribute those we will review again.

**Comment by sepek** [comment]
This PR can be closed after https://github.com/rundeck/terraform-provider-rundeck/pull/89 has been merged

**Pull request closed without merging**
