### PR TITLE
Adding type field to options to allow file upload

### PR DESCRIPTION
**Pull request by kurtmc**

### CODE REVIEW

**Comment by kurtmc** [comment]
@ProTip Would you be able to review this PR?

**Comment by fdevans** [comment]
@qualman can likely help

**Comment by fdevans** [comment]
@kurtmc Can you provide some updates to the docs with this and some steps about how to confirm it's working?

**Comment by kurtmc** [comment]
Since it takes too long for features to get reviewed and merged in this provider, I have decided to maintain my own fork and publish it on terraform registry:
https://github.com/halter/terraform-provider-rundeck
https://registry.terraform.io/providers/halter/rundeck/latest/docs

Feel free to pull changes from that repository. I probably won't open any new PRs here.

**Pull request closed without merging**
