### PR TITLE
Fresh pull request

### PR DESCRIPTION
**Pull request by virgilbourassa**

### CODE REVIEW

**Comment by ProTip** [comment]
Hi @virgilbourassa ,

Cheers for this!  Would you be able to:
* Rebase the branch on master to get the CI/CD acceptance tests running
* Update the PR with a description of the changes/enhancements
* Add acceptance tests to cover the new/change functionality?

I'm hoping to get all the PRs reviewed/tested early next week!

**Comment by virgilbourassa** [comment]
Greg,

Thanks for the suggestions. I'm happy to do that.
I'm new to a) open-source contributing, b) the Go language, and c) Terraform providers, so please bear with my ignorance. As I was putting these features in, my IntelliJ IDE suggested I update my go modules, so I did. Now it seems that it's put me ahead of the modules used in the open-source repo, so I'm having to backtrack. Is there a way to 'reset' my external libraries to match that of the repo?
Thanks for your help!
Virgil


    On Friday, December 18, 2020, 11:50:24 AM PST, Greg Zapp <notifications@github.com> wrote:  
 
 


Hi @virgilbourassa ,

Cheers for this! Would you be able to:
   
   - Rebase the branch on master to get the CI/CD acceptance tests running
   - Update the PR with a description of the changes/enhancements
   - Add acceptance tests to cover the new/change functionality?

I'm hoping to get all the PRs reviewed/tested early next week!

**Comment by ProTip** [comment]
@virgilbourassa ,

I haven't worked much with Go modules myself either(just sporadically on this project). Restoring `go.mod` and `go.sum` from master may do the trick though.

**Comment by virgilbourassa** [comment]
Greg,
I followed your advice and then did 'go mod tidy', which got me back on track. 
Then I discovered that the command job reference node filters were inconsistently implemented and not working, so revised that.
Afterwards, I saw issues in the acceptance tests and fixed those.
Now, it builds and runs for me, but not for you - something about not finding the packages in the current directory. Is this on my end or yours?
Thanks again for your help,
Virgil

    On Tuesday, December 22, 2020, 02:50:35 PM PST, Greg Zapp <notifications@github.com> wrote:  
 
 


@virgilbourassa ,

I haven't worked much with Go modules myself either(just sporadically on this project). Restoring go.mod and go.sum from master may do the trick though.

**Comment by virgilbourassa** [comment]
Greg,
Travis CI - Test and Deploy with Confidence


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Travis CI - Test and Deploy with Confidence

Travis CI enables your team to test and ship your apps with confidence. Easily sync your projects with Travis CI...
 |

 |

 |




I am unable to recreate this problem on my end. Any advice? 
Thanks,
Virgil

    On Thursday, December 24, 2020, 11:32:37 AM PST, Virgil Bourassa <virgil_bourassa@yahoo.com> wrote:  
 
  Greg,
I followed your advice and then did 'go mod tidy', which got me back on track. 
Then I discovered that the command job reference node filters were inconsistently implemented and not working, so revised that.
Afterwards, I saw issues in the acceptance tests and fixed those.
Now, it builds and runs for me, but not for you - something about not finding the packages in the current directory. Is this on my end or yours?
Thanks again for your help,
Virgil

    On Tuesday, December 22, 2020, 02:50:35 PM PST, Greg Zapp <notifications@github.com> wrote:  
 
 


@virgilbourassa ,

I haven't worked much with Go modules myself either(just sporadically on this project). Restoring go.mod and go.sum from master may do the trick though.

**Comment by ProTip** [comment]
Hi @virgilbourassa ,

Are you able to see the github actions build results? The errors I'm seeing are:

```
rundeck/provider.go:39:4: cannot use resourceRundeckJob() (type *"github.com/hashicorp/terraform/helper/schema".Resource) as type *"github.com/hashicorp/terraform-plugin-sdk/helper/schema".Resource in map value
# github.com/hashicorp/terraform-plugin-sdk/internal/earlyconfig
Error: ../../../go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/earlyconfig/config.go:89:20: cannot range over reqs (type *tfconfig.ProviderRequirement)
FAIL	github.com/terraform-providers/terraform-provider-rundeck/rundeck [build failed]
```

**Comment by virgilbourassa** [comment]
Greg, 

Yes, I fixed those issues. I’m having trouble putting them in my other branch now. It’s got me stumped. I think it’s saying it can’t find the code it just built. I can’t recreate the issue locally. Any ideas?

Thanks again,

Virgil

**Comment by virgilbourassa** [comment]
Greg, I'm going to close this PR in favor of PR #63, since that has the latest fixes. Thanks.

**Pull request closed without merging**
