### PR TITLE
Clean feature additions

### PR DESCRIPTION
**Pull request by virgilbourassa**
Only including files I changed intentionally.

### CODE REVIEW

**Comment by fdevans** [comment]
thanks for the PR @virgilbourassa.  I merged a fix for the continuous integration test just now.  In order to approve this PR we'll need context for what changes are made, and what we should expect it to do when we QA test it.

**Comment by virgilbourassa** [comment]
@fdevans Forrest, here's a list of the changes made.

Rundeck Terraform Provider changes

Interface and Documentation
	rundeck_job
		Made node filters interface consistent, changing it from nodefilters to node_filters
		Added exclude_filter to node_filters block
		Added time_zone
		Added retry
		Elaborated documentation on command_ordering_strategy to include “parallel”
		Added node_filter_exclude_query
		Indicated that node_filter_exclude_precedence is deprecated
		Added global_log_filter
		Added label
		Added script_interpreter as a block containing invocation_string and args_quoted
		
Makefile
	format before build
	build a MacBook binary

Added to Job configuration:
	TimeZone 
	Label
	GlobalLogFilters
	Retry
	ContinueNextNodeOnError
	NodeFilterExcludeQuery

Added to Job Command configuration	
	KeepGoingOnSuccess
	ErrorHandler
	ScriptInterpreter (fully implemented)

Added to JobNodeFilter
	ExcludeQuery

Bug fixes
	Cleaned up linter warnings
	Added missing error checks
	JobScheduleMonth Day attribute can’t be empty
	JobCommandSequence ContinueOnError can be empty
	JobNodeFilter ExcludePrecedence can be empty
	JobNodeFilter ExcludePrecedence had wrong default value
	Removed ExcludePrecedece from JobDispatch
	Clarified JobDispatch ContinueOnError as ContinueNextNodeOnError and made it optional
	Fully implemented ErrorHandler
	“description” and enabled by correcting a spelling mistake
	Enforced correctness on schedule cronspec, provide error messages when malformed
	Unnecessary state changes fixed (used to always rebuild)
	Corrected test list syntax

**Review by ltamaster — APPROVED** [review]
tested. 
There are improvements we can do in another PR:
* add a retry_delay to the job definition (this PR just add the retry attribute)
* add log filters at the workflow step level
* add more documentation (an example) of how use the global job filter

**Comment by virgilbourassa** [comment]
Jason,
I'm happy to rebase. And I can take out the linux-specific build.
I'll send another PR your way tomorrow.
Virgil


    On Thursday, May 20, 2021, 02:14:18 PM PDT, Jason Qualman ***@***.***> wrote:  
 
 


@qualman commented on this pull request.

In GNUmakefile:
> @@ -5,8 +5,9 @@ PKG_NAME=rundeck
 
 default: build
 
-build: fmtcheck
-	go install
+build: fmt fmtcheck
+	env go install
+	env GOOS=linux GOARCH=amd64 go install

Hi @virgilbourassa, one last thing before we merge. Can you tell us about the inclusion of this line? I may be missing something, but I am not sure we'll want to hardcode an OS and Architecture into the makefile.

Also, I think you'll need a rebase from rundeck:master. My understanding is the CI tests are failing on a fixed bug.

**Comment by virgilbourassa** [comment]
Jason,
Rebased, and took out the linux-specific build. Pushed to PR branch. 
Thanks,
Virgil

    On Thursday, May 20, 2021, 09:07:07 PM PDT, Virgil Bourassa ***@***.***> wrote:  
 
  Jason,
I'm happy to rebase. And I can take out the linux-specific build.
I'll send another PR your way tomorrow.
Virgil


    On Thursday, May 20, 2021, 02:14:18 PM PDT, Jason Qualman ***@***.***> wrote:  
 
 


@qualman commented on this pull request.

In GNUmakefile:
> @@ -5,8 +5,9 @@ PKG_NAME=rundeck
 
 default: build
 
-build: fmtcheck
-	go install
+build: fmt fmtcheck
+	env go install
+	env GOOS=linux GOARCH=amd64 go install

Hi @virgilbourassa, one last thing before we merge. Can you tell us about the inclusion of this line? I may be missing something, but I am not sure we'll want to hardcode an OS and Architecture into the makefile.

Also, I think you'll need a rebase from rundeck:master. My understanding is the CI tests are failing on a fixed bug.

**Comment by qualman** [comment]
Thank you @virgilbourassa ! Looks like I am not able to get this merged, but I'll grab someone who can get me access.

**Pull request merged**
